### ISSUE TITLE
error when I press on apply

### ISSUE THREAD

**Issue by yoann56100** [Joshuarox100/VRC-Avatar-Scaling#8]
When I press apply I get the error
![Capture](https://user-images.githubusercontent.com/33899467/94993195-939e0100-058f-11eb-9e10-8c15026102ef.PNG)

**Comment by yoann56100** [comment]
I managed to solve it but now it got this 
![Capture](https://user-images.githubusercontent.com/33899467/95011959-03b29280-0635-11eb-9b6e-b3f2c97f3ed4.PNG)

**Comment by haolink** [comment]
Please read the Readme: https://github.com/Joshuarox100/VRC-Avatar-Scaling/blob/master/README.md - this component unfortunately is currently broken, it worked in the VRChat Avatars 3.0 beta - we can only hope for it to return soon!

**Comment by yoann56100** [comment]
sometimed it work and sometimes not
in game i can change my size but I fly
